### ISSUE TITLE
font styling - headers & forms

### ISSUE THREAD

**Issue by Cdelorm** [delorm-designs/tpl_csl_joomla_bootstrap_3#7]
Need to make the font styling the same across the various pages, including the headers and the fonts for the form pages. :-)

**Comment by rpcoomes** [comment]
Have confirmed that the "auto" generated layout for "2 Lines (XHTML)" is missing the CSS formatting options to make the "legend" tag look the same as "H1" headers.  I believe in previous sites we over-ride the auto-generated layout and changed the "legend" tag to an "H1" tag.

I will add CSS formatting to the "legend" tag for the "2 Lines (XHTML)" auto-generated layout in RS Forms to correct this.

**Comment by rpcoomes** [comment]
Recent commits to master branch adds back missing form styles and updates several font styles.  We are also adding more control of individual header (h1-h6) font sizes to over-ride calculated style values.

Going to close this as resolved with latest master commits.
